language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: petra-deploy
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: g4I6mArzY+SlPHnjDNIZOPUzfvCsZcBob7BLzwoWi6yAlvlAhM+AlDfC0OdTdE+hQXhRcinwfQlh1y4WsoWOlQRbG1fvVk6mXOzHrNvvgWj4J6FJnX9/zyUr/3gg/2cpcOWZ/RRsa95u3LK1nDBDaCmp1ms0Ja3Apo0fjB5k9Ixkpx2p84isVSPMQFQMF5goOVP/d5QoysUXlmGpUX6rC6wLPuuDnf+yEp8Q6u79Ei89avGBfKzzc68/4O76NqmhzGMklgWv1rlQOOYKmR2vpEj1T/Y1oHWXVkXZ1iYt+/XV8hIvz53/igMfvroQ2UygVqiLxOYWPiAw6SjJhpxtR4c0O47IQcpqjotSYJhDXmU0I42Wom4hjiCcls/oT4N1XxvS9GrEAWGOi5jKFeeVKmj7SDX7DzxMHVJXiOz+JIwN+HDTPD4tP/FS60GVjiast2puaAxzxFMVAIUJMP9SIvRWYP+oY1EeEecAcJRq/qwK6O5rQtKpEv6dsC10wIax0H2yi94EQ62F/fG5BmwWJSptwhvVrB/2KzYxNYBptnRVrqYKdZseBr0KaRoBbMQQuwpjg/R8jcDMiErk/2Vray4bSbqgBdSwm5U50Gp/Z26GWmE+vfIRfhEd2vpaootMMv5y6qX6rtHFshFyFMJGdA0I+9zAK1IRyem9nXSfYIs=
